### ISSUE TITLE
change dictionary to "mecab-ipadic-neologd"?

### ISSUE THREAD

**Issue by shilik** [dttvn0010/mecab_dart#5]
Is it possible for "mecab-ipadic-neologd" as dictionary rather than the default "ipadic"?
I have tried to change the dictionary files and tested with "8月3日に放送された「中居正広の金曜日のスマイルたちへ」(TBS系)で、1日たった5分でぽっこりおなかを解消するというダイエット方法を紹介。キンタロー。のダイエットにも密着。" ,but the result was the same.

By the way, flutter 3 supports more platforms, it would be greatly appreciated if mecab_dart can extends its support of platforms as well.

**Comment by dttvn0010** [comment]
Have you changed this line to point to your dict : https://github.com/dttvn0010/mecab_dart/blob/master/example/lib/main.dart#L33 ?
You may also need your dict to the asset path if you have not: https://github.com/dttvn0010/mecab_dart/blob/master/example/pubspec.yaml#L42

**Comment by shilik** [comment]
I have made the modifications for the paths as you mentioned accordingly. But still got the same results.

**Comment by pyt3h** [comment]
Here is the result when I use the `ipadic-neologd` dictionary. Is it as expected? 
![Simulator Screen Shot - iPhone 8 - 2022-08-08 at 10 35 11](https://user-images.githubusercontent.com/99658549/183333483-6f5cc1af-f519-4f81-a98b-b935f61b56f1.png)

**Comment by shilik** [comment]
yes, this what I am exactly looking forward.

**Comment by pyt3h** [comment]
Can you try to clean the project first:
`flutter clean && flutter pub get && cd ios/ && pod install `
?

**Comment by shilik** [comment]
Well, I have checked all the settings to make sure everything should be fine and did what you have suggested.
Unfortunately, I got the same result. One thing I noticed that after executing the command it shows some messages, I wonder if this is reason that cause the mecab-ipadic-neologd fail to work as expect?

pubspec.yaml  
assets:
     - assets/ipadic-neologd/

code:
await tagger.init("assets/ipadic-neologd", true);


<img width="267" alt="Snipaste_2022-08-08_12-12-57" src="https://user-images.githubusercontent.com/1404868/183354677-fd9fbc33-af54-4518-a421-580db269bab4.png">
<img width="976" alt="Snipaste_2022-08-08_14-40-05" src="https://user-images.githubusercontent.com/1404868/183355209-d1f89aa6-2379-454f-9a23-d6255dfb5fbc.png">

**Comment by pyt3h** [comment]
I committed  to the example to the new  branch here: https://github.com/dttvn0010/mecab_dart/tree/ipadic-neologd/example
The dictionary is too large to be uploaded to github, please download it from here: http://103.124.94.100/mecab-ipadic-neologd.zip  and extract to the assets folder

**Comment by shilik** [comment]
@pyt3h  Thank you very much. I have tried your dictionary but still the same result.
I will create a new project and give a try again. Thanks for your generous help anyway.

**Comment by shilik** [comment]
By the way, I noticed that a variable dicdir has a default setting as shown in the picture.
Maybe this is the root of the problem?

<img width="684" alt="Snipaste_2022-08-09_14-38-20" src="https://user-images.githubusercontent.com/1404868/183581278-d1301354-1400-48f3-9df6-9a588ead88e8.png">

**Comment by pyt3h** [comment]
You are right.
The app will copy the dictionary from the asset dir to the application document directory so that the mecab engine can access the dictionary, but it will only do so in the first time. Since the name of the document directory is set to "ipadic", when you have a new dictionary in the asset folder, it will not be copied to the document directory anymore.
I will fix this by changing the name of the document directory to the same name of the dictionary the asset folder. In the mean time, you can have a quick fix by reinstall the app in your phone, as this will erase the old dictionary.

**Comment by pyt3h** [comment]
I made the update here: https://github.com/dttvn0010/mecab_dart/blob/ipadic-neologd/lib/mecab_dart.dart#L68-L69
Please see if it helps to resolve the issue in your app, if yes, I will merge the update to master.

**Comment by shilik** [comment]
@pyt3h  Finally it works as expected. Thank you very much for the great plugin, hope I can use it to create not only for mobile devices, but also for the web and standalone applications as well. 
 
Don't forget to add "import 'package:path/path.dart';" in the file or an error of "basename not defined" will popup.

<img width="683" alt="Snipaste_2022-08-09_16-52-29" src="https://user-images.githubusercontent.com/1404868/183608267-beea43a0-f948-4c74-95fa-e18c3b8b36f5.png">
